// This file was generated by Gemini AI
//
// gcc -O3 ntp-diff.c -o ntp-diff
// ./ntp-diff 192.168.40.190 time.nist.gov 5

// This file was generated by Gemini AI (Modified for Seconds output & Final Summary)
//
// gcc -O3 ntp-diff.c -o ntp-diff
// ./ntp-diff 192.168.40.190 time.nist.gov 5

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netdb.h>
#include <stdint.h>
#include <time.h>
#include <math.h>
#include <signal.h> // Added for Ctrl+C handler

#define NTP_PORT "123"
#define NTP_PACKET_SIZE 48
#define NTP_TO_UNIX_EPOCH 2208988800ULL

// Global metrics for the Ctrl+C Final Summary
volatile sig_atomic_t keep_running = 1;
int global_valid_samples = 0;
double global_sum_drift = 0.0;
double global_sum_jitter_dev = 0.0;
const char *global_sample_host = NULL;
const char *global_ref_host = NULL;

struct ntp_packet {
    uint8_t li_vn_mode;      
    uint8_t stratum;         
    uint8_t poll;            
    uint8_t precision;       
    uint32_t rootDelay;      
    uint32_t rootDispersion; 
    uint32_t refId;          
    uint32_t refTm_s;        
    uint32_t refTm_f;        
    uint32_t origTm_s;       
    uint32_t origTm_f;       
    uint32_t rxTm_s;         
    uint32_t rxTm_f;         
    uint32_t txTm_s;         
    uint32_t txTm_f;         
};

// Signal Interrupt Handler
void handle_sigint(int sig) {
    (void)sig;
    keep_running = 0;
}

// DNS Resolution
int resolve_dns(const char *host, struct sockaddr_in *out_addr) {
    struct addrinfo hints, *res;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;       
    hints.ai_socktype = SOCK_DGRAM;  

    int status = getaddrinfo(host, NTP_PORT, &hints, &res);
    if (status != 0) {
        fprintf(stderr, "DNS Error for '%s': %s\n", host, gai_strerror(status));
        return -1;
    }
    memcpy(out_addr, res->ai_addr, sizeof(struct sockaddr_in));
    freeaddrinfo(res);
    return 0;
}

// Network I/O and raw seconds offset calculation
int get_ntp_offset_seconds(int sock_fd, const struct sockaddr_in *target_addr, double *out_offset) {
    struct ntp_packet packet;
    struct timespec local_ts;
    socklen_t addr_len = sizeof(struct sockaddr_in);

    memset(&packet, 0, sizeof(struct ntp_packet));
    packet.li_vn_mode = 0x1B; 

    if (sendto(sock_fd, &packet, NTP_PACKET_SIZE, 0, (struct sockaddr *)target_addr, addr_len) < 0) {
        return -1;
    }
    if (recvfrom(sock_fd, &packet, NTP_PACKET_SIZE, 0, (struct sockaddr *)target_addr, &addr_len) < 0) {
        return -1; 
    }

    clock_gettime(CLOCK_REALTIME, &local_ts);

    uint32_t ntp_secs = ntohl(packet.txTm_s);
    uint32_t ntp_frac = ntohl(packet.txTm_f);

    int64_t server_secs = (int64_t)ntp_secs - NTP_TO_UNIX_EPOCH;
    
    // CHANGED: Math updated to calculate absolute raw seconds directly
    double server_frac_s = (double)ntp_frac / 4294967296.0;
    double total_server_s = (double)server_secs + server_frac_s;
    double total_local_s = (double)local_ts.tv_sec + ((double)local_ts.tv_nsec / 1000000000.0);

    *out_offset = total_server_s - total_local_s;
    return 0;
}

int main(int argc, char *argv[]) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <sample_server> <reference_server> <num_samples>\n", argv[0]);
        return EXIT_FAILURE;
    }

    const char *sample_host = argv[1];
    const char *reference_host = argv[2];
    int num_samples = atoi(argv[3]);

    // Save configuration states to global registers for summary dump
    global_sample_host = sample_host;
    global_ref_host = reference_host;

    if (num_samples <= 0) {
        fprintf(stderr, "Error: Samples must be > 0\n");
        return EXIT_FAILURE;
    }

    struct sockaddr_in sample_addr, ref_addr;
    printf("Resolving domains...\n");
    if (resolve_dns(sample_host, &sample_addr) != 0 || resolve_dns(reference_host, &ref_addr) != 0) {
        return EXIT_FAILURE;
    }

    int sock_fd = socket(AF_INET, SOCK_DGRAM, 0);
    if (sock_fd < 0) {
        perror("Socket creation failed");
        return EXIT_FAILURE;
    }

    // Set 1.5-second socket timeout
    struct timeval tv = {.tv_sec = 1, .tv_usec = 500000};
    setsockopt(sock_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    // Register Ctrl+C interruption hook
    signal(SIGINT, handle_sigint);

    printf("Executing trace loop (%d samples). Press Ctrl+C to stop early:\n\n", num_samples);
    
    // CHANGED: Formatted layout headers updated to reflect seconds context
    printf("%-5s | %-16s | %-15s | %-14s\n", "Step", "True Drift (s)", "Rolling Avg (s)", "Jitter (s)");
    printf("-----------------------------------------------------------------\n");

    double sum_drift = 0.0;
    double prev_drift = 0.0;
    double sum_jitter_dev = 0.0;
    int valid_samples = 0;

    // Loop runs while total count is under target and keep_running isn't cleared by Ctrl+C
    for (int i = 1; i <= num_samples && keep_running; i++) {
        double sample_offset = 0.0;
        double ref_offset = 0.0;

        int ret_s = get_ntp_offset_seconds(sock_fd, &sample_addr, &sample_offset);
        int ret_r = get_ntp_offset_seconds(sock_fd, &ref_addr, &ref_offset);

        if (ret_s != 0 || ret_r != 0) {
            printf("%-5d | %-16s | %-15s | %-14s\n", i, "ERROR/TIMEOUT", "N/A", "N/A");
            continue;
        }

        valid_samples++;
        global_valid_samples = valid_samples; // Synchronize to global space
        
        double current_drift = sample_offset - ref_offset;
        
        sum_drift += current_drift;
        global_sum_drift = sum_drift;
        
        double rolling_avg = sum_drift / valid_samples;

        double rolling_jitter = 0.0;
        if (valid_samples > 1) {
            double current_diff = fabs(current_drift - prev_drift);
            sum_jitter_dev += current_diff;
            global_sum_jitter_dev = sum_jitter_dev;
            rolling_jitter = sum_jitter_dev / (valid_samples - 1);
        }

        // CHANGED: Format specifiers modified to %+.6f to force 6 decimal places (microsecond resolution)
        printf("%-5d | %-+16.6f | %-+15.6f | %-14.6f\n", 
               i, current_drift, rolling_avg, rolling_jitter);
        fflush(stdout);

        prev_drift = current_drift;

        if (i < num_samples && keep_running) {
            // Anti-throttling responsive split loop (breaks quickly if Ctrl+C is pressed)
            for (int d = 0; d < 25 && keep_running; d++) {
                usleep(10000); 
            }
        }
    }

    close(sock_fd);

    // Final Summary Scorecard Implementation
    printf("\n\n-----------------------------------------------------------------\n");
    printf("                       FINAL DRIFT SUMMARY                       \n");
    printf("-----------------------------------------------------------------\n");
    printf("Sample Server Node:      %s\n", global_sample_host);
    printf("Reference Clock Source:  %s\n", global_ref_host);
    printf("Total Valid Traces:      %d\n", global_valid_samples);
    
    if (global_valid_samples > 0) {
        double final_avg = global_sum_drift / global_valid_samples;
        double final_jitter = (global_valid_samples > 1) ? (global_sum_jitter_dev / (global_valid_samples - 1)) : 0.0;
        printf("Final Average Drift:     %+.6f seconds\n", final_avg);
        printf("Final Mean Jitter:       %.6f seconds\n", final_jitter);
    } else {
        printf("Final Performance:       No successful samples captured.\n");
    }
    printf("-----------------------------------------------------------------\n");

    return EXIT_SUCCESS;
}
